### ISSUE TITLE
when content of email have image it dont show body of message - {error: 'Error: Request failed with status code 500'}

### ISSUE THREAD

**Issue by allanian** [uilicious/inboxkitten#62]
Hello,
we installed inboxkitten with docker and configure nginx over inboxkitten with that config:
when we send email with only text, its working perfect, but when we add some images to text, its failing with status code 500.
Can you help us?
```
server {
listen 80;
server_name inbox.company.com;
return 301 https://$host$request_uri;
}

server {
    listen   443 ssl;
    server_name inbox.company.com;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES25$
    ssl_prefer_server_ciphers on;
    ssl_certificate  /etc/nginx/ssl/company.crt;
    ssl_certificate_key /etc/nginx/ssl/company.key;
    access_log /var/log/nginx/mail.access.log;
    error_log /var/log/nginx/mail.error.log;
    client_max_body_size 20m;
    location / {
        proxy_pass  http://127.0.0.1:8000;
        proxy_redirect                  off;
        proxy_set_header                Host $host;
        proxy_set_header                X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
}
```
docker-compose:
```
version: "3"
services:
  inboxkitten:
    image: uilicious/inboxkitten
    container_name: mail
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      MAILGUN_EMAIL_DOMAIN: "inbox.company.com"
      MAILGUN_API_KEY: "api-key-mailgun"
      WEBSITE_DOMAIN: "inbox.company.com"
    network_mode: host
```
